graylog:
  tags:
    install-elasticsearch: false
    install-mongodb: false
  graylog:
    image:
      tag: "4.2.5"
    input:
      udp:
        service:
          type: ClusterIP
        ports:
          - name: syslog
            port: 1514
    rootUsername: "Admin"
    rootEmail: "wassalni.tech@gmail.com"
    existingRootSecret: root-secret
    elasticsearch:
      hosts:
        - elastic.database:9200
      uriSecretKey: uri
      uriSecretName: graylog-elastic-secret
    mongodb:
      uriSecretName: graylog-mongo-secret
      uriSecretKey: uri
